version: 0.2

phases:
  install:
    commands:
      # Upgrade AWS CLI to the latest version
      - pip install --upgrade awscli

  build:
      ./gradlew clean build
  post_build:
    commands:
      - echo Build started on `date`
      - aws cloudformation package --template template.yml --s3-bucket $S3_BUCKET --output-template template-export.yml

artifacts:
  files:
    - template-export.yml



