AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: 'EC2 templace'


Parameters:
  ProjectId:
    Type: String
  Stage:
    Type: String
    Description: Deployment stage. E.g. test, prod, etc.
  Branch:
    Type: String
  CodeBucket:
    Type: String
  InitFunctionName:
    Type: String
  DestroyFunctionName:
    Type:  String


Resources:
  SmallServer:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-08660f1c6fb6b01e7
      InstanceType: t2.micro


  Init:
    Type: AWS::Serverless::Function
    Properties:
      Handler: handlers.SimplePipelineLambdaFunction::handleRequest
      FunctionName: !Ref InitFunctionName
      Runtime: java8
      CodeUri: build/libs/pipeline-example-fat.jar
      Policies:
        Version: '2012-10-17'
        Statement:
          - Action:
              - lambda:InvokeFunction
              - codepipeline:PutJobFailureResult
              - codepipeline:PutJobSuccessResult
            Effect: Allow
            Resource: "*"
          - Effect: Allow
            Action: iam:CreateServiceLinkedRole
            Resource: "arn:aws:iam::*:role/aws-service-role/*"
      MemorySize: 256
      Timeout: 900


  Destroy:
    Type: AWS::Serverless::Function
    Properties:
      Handler: handlers.SimplePipelineLambdaFunction::handleRequest
      FunctionName: !Ref DestroyFunctionName
      Runtime: java8
      CodeUri: build/libs/pipeline-example-fat.jar
      Policies:
        Version: '2012-10-17'
        Statement:
          - Action:
              - lambda:InvokeFunction
              - codepipeline:PutJobFailureResult
              - codepipeline:PutJobSuccessResult
            Effect: Allow
            Resource: "*"
          - Effect: Allow
            Action: iam:CreateServiceLinkedRole
            Resource: "arn:aws:iam::*:role/aws-service-role/*"
      MemorySize: 256
      Timeout: 900

