AWSTemplateFormatVersion: '2010-09-09'
Description: 'EC2 templace'


Parameters:
  ProjectId:
    Type: String
  Stage:
    Type: String
    Description: Deployment stage. E.g. test, prod, etc.
  Branch:
    Type: String
  CodeBucket:
    Type: String
  InitFunctionName:
    Type: String
  DestroyFunctionName:
    Type:  String


Resources:
  SmallServer:
    Type: AWS::EC2::Instance
    Properties:
      AvailabilityZone: eu-west-1a
      ImageId: ami-08660f1c6fb6b01e7
      InstanceType: t2.micro

