AWSTemplateFormatVersion: '2010-09-09'
Description: 'EC2 templace'


Parameters:
  ProjectId:
    Type: String
    Default: hello
  Stage:
    Type: String
    Description: Deployment stage. E.g. test, prod, etc.
    Default: hello
  Branch:
    Type: String
    Default: hello
  CodeBucket:
    Type: String
    Default: hello
  InitFunctionName:
    Type: String
    Default: hello
  DestroyFunctionName:
    Type:  String
    Default: hello


Resources:
  SmallServer:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-08660f1c6fb6b01e7
      InstanceType: t2.micro
      KeyName: orestis-key


