AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: 'EC2 templace'


Parameters:
  ProjectId:
    Type: String
    Default: hello
  Stage:
    Type: String
    Description: Deployment stage. E.g. test, prod, etc.
    Default: hello
  Branch:
    Type: String
    Default: hello
  CodeBucket:
    Type: String
    Default: hello
  InitFunctionName:
    Type: String
    Default: hello
  DestroyFunctionName:
    Type:  String
    Default: hello


Resources:
  SmallServer:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-08660f1c6fb6b01e7
      InstanceType: t2.micro
      KeyName: orestis-key


  Init:
    Type: AWS::Serverless::Function
    Properties:
      Handler: handlers.SimplePipelineLambdaFunction::handleRequest
      FunctionName: !Ref InitFunctionName
      Runtime: java8
      CodeUri: build/libs/pipeline-example.jar
      Policies:
        Version: '2012-10-17'
        Statement:
          - Action:
              - lambda:InvokeFunction
              - codepipeline:PutJobFailureResult
              - codepipeline:PutJobSuccessResult
            Effect: Allow
            Resource: "*"
          - Effect: Allow
            Action: iam:CreateServiceLinkedRole
            Resource: "arn:aws:iam::*:role/aws-service-role/*"
      MemorySize: 128
      Timeout: 900


  Destroy:
    Type: AWS::Serverless::Function
    Properties:
      Handler: handlers.SimplePipelineLambdaFunction::handleRequest
      FunctionName: !Ref DestroyFunctionName
      Runtime: java8
      CodeUri: build/libs/pipeline-example.jar
      Policies:
        Version: '2012-10-17'
        Statement:
          - Action:
              - lambda:InvokeFunction
              - codepipeline:PutJobFailureResult
              - codepipeline:PutJobSuccessResult
            Effect: Allow
            Resource: "*"
          - Effect: Allow
            Action: iam:CreateServiceLinkedRole
            Resource: "arn:aws:iam::*:role/aws-service-role/*"
      MemorySize: 128
      Timeout: 900

